#!/bin/sh ‚‹°›€‡ß

#SET_PATH - This line is a placeholder to ease patching this script.

# Instead of unsetting XZ_OPT, just make sure that xz will use file format
# autodetection. This way memory usage limit and thread limit can be
# specified via XZ_OPT.
xz='xz --format=auto'

version='xzless (XZ Utils) 5.1.4beta'

usage="Usage: ${0##*/} [OPTION]... [FILE]...
Like 'less', but operate on the uncompressed contents of xz compressed FILEs.

Options are the same as for 'less'.

Report bugs to <lasse.collin@tukaani.org>."

case $1 in
	--help)    echo "$usage" || exit 2; exit;;
	--version) echo "$version" || exit 2; exit;;
esac

if test "${LESSMETACHARS+set}" != set; then
	# Work around a bug in less 394 and earlier;
	# it mishandles the metacharacters '$%=~'.
	space=' '
	tab='	'
	nl='
'
	LESSMETACHARS="$space$tab$nl'"';*?"()<>[|&^`#\$%=~'
fi

if test "$(less -V | { read less ver re && echo ${ver}; })" -ge 429; then
	# less 429 or later: LESSOPEN pipe will be used on
	# standard input if $LESSOPEN begins with |-.
	LESSOPEN="|-$xz -cdfq -- %s"
else
	LESSOPEN="|$xz -cdfq -- %s"
fi
export LESSMETACHARS LESSOPEN

exec less "$@"
